mutation {
  menuUpdate(
    id: "gid://shopify/Menu/313896927523"
    title: "Footer Learn"
    items: [
      { title: "About Us", type: HTTP, url: "/pages/our-story" }
      { title: "Press", type: HTTP, url: "/pages/press" }
      { title: "Journal", type: HTTP, url: "/blogs/news" }
      { title: "Collaborations", type: HTTP, url: "/pages/collaborations" }
      { title: "Wholesale", type: HTTP, url: "/pages/wholesale" }
      { title: "Compare Styles", type: HTTP, url: "/pages/compare-open-closed-sole" }
    ]
  ) {
    menu { handle items { title url } }
    userErrors { field message }
  }
}
