mutation {
  menuUpdate(
    id: "gid://shopify/Menu/313154371875"
    title: "M4 Menu"
    items: [
      {
        title: "Grippy Shoes"
        type: HTTP
        url: "/collections/barre-pilates-yoga-shoe-sock-footwear"
        items: [
          { title: "Shop All Grippy Shoes", type: HTTP, url: "/collections/barre-pilates-yoga-shoe-sock-footwear" }
          { title: "Open Sole", type: HTTP, url: "/products/studio-performance-skin-footwear" }
          { title: "Closed Sole", type: HTTP, url: "/products/best-reformer-pilates-legree-workout-shoes" }
          { title: "Outdoor", type: HTTP, url: "/products/aquatic-performance-skins" }
          { title: "Compare Styles", type: HTTP, url: "/pages/compare-open-closed-sole" }
        ]
      }
      {
        title: "Apparel"
        type: HTTP
        url: "/collections/apparel"
        items: [
          { title: "Shop All Apparel", type: HTTP, url: "/collections/apparel" }
          { title: "Tops", type: HTTP, url: "/products/barreletics-performance-fabric-yoga-t-shirts" }
          { title: "Bottoms", type: HTTP, url: "/products/lightly-padded-knee-yoga-pant-black" }
        ]
      }
      {
        title: "Collaborations"
        type: HTTP
        url: "/pages/collaborations"
        items: [
          { title: "Coperni", type: HTTP, url: "/products/barreletics-x-coperni-closed-sole" }
          { title: "Free People", type: HTTP, url: "/pages/free-people" }
        ]
      }
      {
        title: "Journal"
        type: HTTP
        url: "/blogs/news"
      }
      {
        title: "About Us"
        type: HTTP
        url: "/pages/our-story"
        items: [
          { title: "Our Story", type: HTTP, url: "/pages/our-story" }
          { title: "Press", type: HTTP, url: "/pages/press" }
        ]
      }
    ]
  ) {
    menu { handle items { title url items { title url } } }
    userErrors { field message }
  }
}
